/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Author;
import org.demo.service.criteria.AuthorCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Author.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface AuthorService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of author
	 */
	public Page<Author> search(Pageable pageable, AuthorCriteria criteria);
	/**
	 * Recover an author following an id.
	 * @param id the given id
	 * @return the author
	 */
	public Author get(Integer id);

	/**
	 * Perform an author deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer id);

	/**
	 * Perform an author creation.
	 * @param author to create
	 * @return created author
	 */
	public Author create(Author author);

	/**
	 * Perform an author update.
	 * @param author to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Author author);

	/**
	 * Test author existence.
	 * @param author to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Author author);
}
