/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Book;
import org.demo.service.criteria.BookCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Book.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface BookService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of book
	 */
	public Page<Book> search(Pageable pageable, BookCriteria criteria);
	/**
	 * Recover an book following an id.
	 * @param id the given id
	 * @return the book
	 */
	public Book get(Integer id);

	/**
	 * Perform an book deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer id);

	/**
	 * Perform an book creation.
	 * @param book to create
	 * @return created book
	 */
	public Book create(Book book);

	/**
	 * Perform an book update.
	 * @param book to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Book book);

	/**
	 * Test book existence.
	 * @param book to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Book book);
}
