/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.BookOrderItem;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for BookOrderItem.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface BookOrderItemService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @return a page of bookOrderItem
	 */
	public Page<BookOrderItem> search(Pageable pageable);
	/**
	 * Recover an bookOrderItem following an id.
	 * @param id the given id
	 * @return the bookOrderItem
	 */
	public BookOrderItem get(Integer bookOrderId, Integer bookId);

	/**
	 * Perform an bookOrderItem deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer bookOrderId, Integer bookId);

	/**
	 * Perform an bookOrderItem creation.
	 * @param bookOrderItem to create
	 * @return created bookOrderItem
	 */
	public BookOrderItem create(BookOrderItem bookOrderItem);

	/**
	 * Perform an bookOrderItem update.
	 * @param bookOrderItem to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(BookOrderItem bookOrderItem);

	/**
	 * Test bookOrderItem existence.
	 * @param bookOrderItem to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(BookOrderItem bookOrderItem);
}
