/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.BookOrder;
import org.demo.service.criteria.BookOrderCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for BookOrder.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface BookOrderService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of bookOrder
	 */
	public Page<BookOrder> search(Pageable pageable, BookOrderCriteria criteria);
	/**
	 * Recover an bookOrder following an id.
	 * @param id the given id
	 * @return the bookOrder
	 */
	public BookOrder get(Integer id);

	/**
	 * Perform an bookOrder deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer id);

	/**
	 * Perform an bookOrder creation.
	 * @param bookOrder to create
	 * @return created bookOrder
	 */
	public BookOrder create(BookOrder bookOrder);

	/**
	 * Perform an bookOrder update.
	 * @param bookOrder to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(BookOrder bookOrder);

	/**
	 * Test bookOrder existence.
	 * @param bookOrder to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(BookOrder bookOrder);
}
