/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import java.math.BigDecimal;
import javax.persistence.*;

import org.demo.entity.BookOrderItem;
import org.demo.entity.BookOrderItemKey;
import org.demo.repository.BookOrderItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 * Service implementation for BookOrderItem.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
public class BookOrderItemServiceImpl implements BookOrderItemService {

	@Autowired
	private BookOrderItemRepository bookOrderItemRepository;

	@Override
	public Page<BookOrderItem> search(Pageable pageable) {
		return bookOrderItemRepository.findAll(pageable);
	}

	@Override
	public BookOrderItem get(Integer bookOrderId, Integer bookId) {
		// Build the composite key
		BookOrderItemKey key = new BookOrderItemKey(bookOrderId, bookId);
		return bookOrderItemRepository.findById(key).orElse(null);
	}

	@Override
	public Boolean delete(Integer bookOrderId, Integer bookId) {
		// Build the composite key
		BookOrderItemKey key = new BookOrderItemKey(bookOrderId, bookId);
		if (bookOrderItemRepository.findById(key) != null) {
			bookOrderItemRepository.deleteById(key);
			return true;
		}
		return false;
	}

	@Override
	public BookOrderItem create(BookOrderItem bookOrderItem) {
		return bookOrderItemRepository.save(bookOrderItem);
	}

	@Override
	public Boolean save(BookOrderItem bookOrderItem) {
		// Build the composite key
		BookOrderItemKey pk = new BookOrderItemKey(bookOrderItem.getBookOrderId(), bookOrderItem.getBookId());
		if (bookOrderItemRepository.findById(pk) != null) {
			bookOrderItemRepository.save(bookOrderItem);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(BookOrderItem bookOrderItem) {
		// Build the composite key
		BookOrderItemKey pk = new BookOrderItemKey(bookOrderItem.getBookOrderId(), bookOrderItem.getBookId());
		return bookOrderItemRepository.existsById(pk);
	}


}

