/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import java.util.Date;
import javax.persistence.*;


import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.demo.entity.BookOrder;
import org.demo.repository.BookOrderRepository;
import org.demo.service.criteria.BookOrderCriteria;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

/**
 * Service implementation for BookOrder.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
public class BookOrderServiceImpl implements BookOrderService {

	@Autowired
	private BookOrderRepository bookOrderRepository;

	@Override
	public Page<BookOrder> search(Pageable pageable, BookOrderCriteria criteria) {
		return bookOrderRepository.findAll(new BookOrderSpecification(criteria), pageable);
	}

	@Override
	public BookOrder get(Integer id) {
		return bookOrderRepository.findById(id).orElse(null);
	}

	@Override
	public Boolean delete(Integer id) {
		if (bookOrderRepository.findById(id) != null) {
			bookOrderRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public BookOrder create(BookOrder bookOrder) {
		return bookOrderRepository.save(bookOrder);
	}

	@Override
	public Boolean save(BookOrder bookOrder) {
		final Integer pk = bookOrder.getId();
		if (bookOrderRepository.findById(pk) != null) {
			bookOrderRepository.save(bookOrder);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(BookOrder bookOrder) {
		return bookOrderRepository.existsById(bookOrder.getId());
	}

	class BookOrderSpecification implements Specification<BookOrder> {

		private BookOrderCriteria criteria;

		public BookOrderSpecification(BookOrderCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<BookOrder> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getShopCode())) {
				predicates.add(builder.like(builder.lower(root.get("shopCode")),
						criteria.getShopCode().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getCustomerCode())) {
				predicates.add(builder.like(builder.lower(root.get("customerCode")),
						criteria.getCustomerCode().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getEmployeeCode())) {
				predicates.add(builder.like(builder.lower(root.get("employeeCode")),
						criteria.getEmployeeCode().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}

