/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Country;
import org.demo.service.criteria.CountryCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Country.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface CountryService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of country
	 */
	public Page<Country> search(Pageable pageable, CountryCriteria criteria);
	/**
	 * Recover an country following an id.
	 * @param id the given id
	 * @return the country
	 */
	public Country get(String code);

	/**
	 * Perform an country deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(String code);

	/**
	 * Perform an country creation.
	 * @param country to create
	 * @return created country
	 */
	public Country create(Country country);

	/**
	 * Perform an country update.
	 * @param country to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Country country);

	/**
	 * Test country existence.
	 * @param country to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Country country);
}
