/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import javax.persistence.*;


import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.demo.entity.Country;
import org.demo.repository.CountryRepository;
import org.demo.service.criteria.CountryCriteria;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Country.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
public class CountryServiceImpl implements CountryService {

	@Autowired
	private CountryRepository countryRepository;

	@Override
	public Page<Country> search(Pageable pageable, CountryCriteria criteria) {
		return countryRepository.findAll(new CountrySpecification(criteria), pageable);
	}

	@Override
	public Country get(String code) {
		return countryRepository.findById(code).orElse(null);
	}

	@Override
	public Boolean delete(String code) {
		if (countryRepository.findById(code) != null) {
			countryRepository.deleteById(code);
			return true;
		}
		return false;
	}

	@Override
	public Country create(Country country) {
		return countryRepository.save(country);
	}

	@Override
	public Boolean save(Country country) {
		final String pk = country.getCode();
		if (countryRepository.findById(pk) != null) {
			countryRepository.save(country);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Country country) {
		return countryRepository.existsById(country.getCode());
	}

	class CountrySpecification implements Specification<Country> {

		private CountryCriteria criteria;

		public CountrySpecification(CountryCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<Country> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getName())) {
				predicates.add(builder.like(builder.lower(root.get("name")),
						criteria.getName().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}

