/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Customer;
import org.demo.service.criteria.CustomerCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Customer.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface CustomerService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of customer
	 */
	public Page<Customer> search(Pageable pageable, CustomerCriteria criteria);
	/**
	 * Recover an customer following an id.
	 * @param id the given id
	 * @return the customer
	 */
	public Customer get(String code);

	/**
	 * Perform an customer deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(String code);

	/**
	 * Perform an customer creation.
	 * @param customer to create
	 * @return created customer
	 */
	public Customer create(Customer customer);

	/**
	 * Perform an customer update.
	 * @param customer to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Customer customer);

	/**
	 * Test customer existence.
	 * @param customer to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Customer customer);
}
