/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import javax.persistence.*;


import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.demo.entity.Publisher;
import org.demo.repository.PublisherRepository;
import org.demo.service.criteria.PublisherCriteria;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Publisher.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Service
public class PublisherServiceImpl implements PublisherService {

	@Autowired
	private PublisherRepository publisherRepository;

	@Override
	public Page<Publisher> search(Pageable pageable, PublisherCriteria criteria) {
		return publisherRepository.findAll(new PublisherSpecification(criteria), pageable);
	}

	@Override
	public Publisher get(Integer code) {
		return publisherRepository.findById(code).orElse(null);
	}

	@Override
	public Boolean delete(Integer code) {
		if (publisherRepository.findById(code) != null) {
			publisherRepository.deleteById(code);
			return true;
		}
		return false;
	}

	@Override
	public Publisher create(Publisher publisher) {
		return publisherRepository.save(publisher);
	}

	@Override
	public Boolean save(Publisher publisher) {
		final Integer pk = publisher.getCode();
		if (publisherRepository.findById(pk) != null) {
			publisherRepository.save(publisher);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Publisher publisher) {
		return publisherRepository.existsById(publisher.getCode());
	}

	class PublisherSpecification implements Specification<Publisher> {

		private PublisherCriteria criteria;

		public PublisherSpecification(PublisherCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<Publisher> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getCountryCode())) {
				predicates.add(builder.like(builder.lower(root.get("countryCode")),
						criteria.getCountryCode().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getName())) {
				predicates.add(builder.like(builder.lower(root.get("name")),
						criteria.getName().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getEmail())) {
				predicates.add(builder.like(builder.lower(root.get("email")),
						criteria.getEmail().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getContact())) {
				predicates.add(builder.like(builder.lower(root.get("contact")),
						criteria.getContact().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getCity())) {
				predicates.add(builder.like(builder.lower(root.get("city")),
						criteria.getCity().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getPhone())) {
				predicates.add(builder.like(builder.lower(root.get("phone")),
						criteria.getPhone().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}

