/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Shop;
import org.demo.service.criteria.ShopCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Shop.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface ShopService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of shop
	 */
	public Page<Shop> search(Pageable pageable, ShopCriteria criteria);
	/**
	 * Recover an shop following an id.
	 * @param id the given id
	 * @return the shop
	 */
	public Shop get(String code);

	/**
	 * Perform an shop deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(String code);

	/**
	 * Perform an shop creation.
	 * @param shop to create
	 * @return created shop
	 */
	public Shop create(Shop shop);

	/**
	 * Perform an shop update.
	 * @param shop to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Shop shop);

	/**
	 * Test shop existence.
	 * @param shop to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Shop shop);
}
