/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Synopsis;
import org.demo.service.criteria.SynopsisCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Synopsis.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface SynopsisService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of synopsis
	 */
	public Page<Synopsis> search(Pageable pageable, SynopsisCriteria criteria);
	/**
	 * Recover an synopsis following an id.
	 * @param id the given id
	 * @return the synopsis
	 */
	public Synopsis get(Integer bookId);

	/**
	 * Perform an synopsis deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer bookId);

	/**
	 * Perform an synopsis creation.
	 * @param synopsis to create
	 * @return created synopsis
	 */
	public Synopsis create(Synopsis synopsis);

	/**
	 * Perform an synopsis update.
	 * @param synopsis to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Synopsis synopsis);

	/**
	 * Test synopsis existence.
	 * @param synopsis to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Synopsis synopsis);
}
