/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service;

import org.demo.entity.Workgroup;
import org.demo.service.criteria.WorkgroupCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Workgroup.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public interface WorkgroupService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @param criteria filters
	 * @return a page of workgroup
	 */
	public Page<Workgroup> search(Pageable pageable, WorkgroupCriteria criteria);
	/**
	 * Recover an workgroup following an id.
	 * @param id the given id
	 * @return the workgroup
	 */
	public Workgroup get(Short id);

	/**
	 * Perform an workgroup deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Short id);

	/**
	 * Perform an workgroup creation.
	 * @param workgroup to create
	 * @return created workgroup
	 */
	public Workgroup create(Workgroup workgroup);

	/**
	 * Perform an workgroup update.
	 * @param workgroup to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(Workgroup workgroup);

	/**
	 * Test workgroup existence.
	 * @param workgroup to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Workgroup workgroup);
}
