/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Customer search.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class CustomerCriteria {

    private String countryCode; 
    private String firstName; 
    private String lastName; 
    private String login; 
    private String password; 
    private String city; 
    private String phone; 
	// Constructor
	public CustomerCriteria() {
		// Needed empty constructor for serialization
	}

	public void setCountryCode(String countryCode) {this.countryCode = countryCode;}
	public String getCountryCode() {return this.countryCode;}
	public void setFirstName(String firstName) {this.firstName = firstName;}
	public String getFirstName() {return this.firstName;}
	public void setLastName(String lastName) {this.lastName = lastName;}
	public String getLastName() {return this.lastName;}
	public void setLogin(String login) {this.login = login;}
	public String getLogin() {return this.login;}
	public void setPassword(String password) {this.password = password;}
	public String getPassword() {return this.password;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setPhone(String phone) {this.phone = phone;}
	public String getPhone() {return this.phone;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(countryCode); 
		sb.append("|"); 
		sb.append(firstName); 
		sb.append("|"); 
		sb.append(lastName); 
		sb.append("|"); 
		sb.append(login); 
		sb.append("|"); 
		sb.append(password); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(phone); 
        return sb.toString();
	}
}
