/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Employee search.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class EmployeeCriteria {

    private String shopCode; 
    private String firstName; 
    private String lastName; 
    private String email; 
	// Constructor
	public EmployeeCriteria() {
		// Needed empty constructor for serialization
	}

	public void setShopCode(String shopCode) {this.shopCode = shopCode;}
	public String getShopCode() {return this.shopCode;}
	public void setFirstName(String firstName) {this.firstName = firstName;}
	public String getFirstName() {return this.firstName;}
	public void setLastName(String lastName) {this.lastName = lastName;}
	public String getLastName() {return this.lastName;}
	public void setEmail(String email) {this.email = email;}
	public String getEmail() {return this.email;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(shopCode); 
		sb.append("|"); 
		sb.append(firstName); 
		sb.append("|"); 
		sb.append(lastName); 
		sb.append("|"); 
		sb.append(email); 
        return sb.toString();
	}
}
