/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Publisher search.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class PublisherCriteria {

    private String countryCode; 
    private String name; 
    private String email; 
    private String contact; 
    private String city; 
    private String phone; 
	// Constructor
	public PublisherCriteria() {
		// Needed empty constructor for serialization
	}

	public void setCountryCode(String countryCode) {this.countryCode = countryCode;}
	public String getCountryCode() {return this.countryCode;}
	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}
	public void setEmail(String email) {this.email = email;}
	public String getEmail() {return this.email;}
	public void setContact(String contact) {this.contact = contact;}
	public String getContact() {return this.contact;}
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}
	public void setPhone(String phone) {this.phone = phone;}
	public String getPhone() {return this.phone;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(countryCode); 
		sb.append("|"); 
		sb.append(name); 
		sb.append("|"); 
		sb.append(email); 
		sb.append("|"); 
		sb.append(contact); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(phone); 
        return sb.toString();
	}
}
