/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Review search.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class ReviewCriteria {

    private String reviewText; 
	// Constructor
	public ReviewCriteria() {
		// Needed empty constructor for serialization
	}

	public void setReviewText(String reviewText) {this.reviewText = reviewText;}
	public String getReviewText() {return this.reviewText;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(reviewText); 
        return sb.toString();
	}
}
