/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Workgroup search.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class WorkgroupCriteria {

    private String name; 
    private String description; 
	// Constructor
	public WorkgroupCriteria() {
		// Needed empty constructor for serialization
	}

	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}
	public void setDescription(String description) {this.description = description;}
	public String getDescription() {return this.description;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(name); 
		sb.append("|"); 
		sb.append(description); 
        return sb.toString();
	}
}
