/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;
import java.util.Date;

/**
 * Hateoas resource associated with Badge.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class BadgeResource extends ResourceSupport {

    private Integer badgeNumber;  
    private Short authorizationLevel;  
    private Date endOfValidity;  

	// Constructor
	public BadgeResource() {
		// Needed empty constructor for serialization
	}

	public Integer getBadgeNumber() {
		return this.badgeNumber;
	}
	public void setBadgeNumber(Integer badgeNumber) {
		this.badgeNumber = badgeNumber;
	}
	public Short getAuthorizationLevel() {
		return this.authorizationLevel;
	}
	public void setAuthorizationLevel(Short authorizationLevel) {
		this.authorizationLevel = authorizationLevel;
	}
	public Date getEndOfValidity() {
		return this.endOfValidity;
	}
	public void setEndOfValidity(Date endOfValidity) {
		this.endOfValidity = endOfValidity;
	}
}
