/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;
import java.math.BigDecimal;

/**
 * Hateoas resource associated with Book.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class BookResource extends ResourceSupport {

	// Because id is reserved in parent class, we can't override the getter.
	@SuppressWarnings("unused")
    private Integer id;  
    private Integer publisherId;  
    private Integer authorId;  
    private String isbn;  
    private String title;  
    private BigDecimal price;  
    private Integer quantity;  
    private Integer discount;  
    private Short availability;  
    private Short bestSeller;  

	// Constructor
	public BookResource() {
		// Needed empty constructor for serialization
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getPublisherId() {
		return this.publisherId;
	}
	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}
	public Integer getAuthorId() {
		return this.authorId;
	}
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}
	public String getIsbn() {
		return this.isbn;
	}
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}
	public String getTitle() {
		return this.title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public BigDecimal getPrice() {
		return this.price;
	}
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	public Integer getQuantity() {
		return this.quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public Integer getDiscount() {
		return this.discount;
	}
	public void setDiscount(Integer discount) {
		this.discount = discount;
	}
	public Short getAvailability() {
		return this.availability;
	}
	public void setAvailability(Short availability) {
		this.availability = availability;
	}
	public Short getBestSeller() {
		return this.bestSeller;
	}
	public void setBestSeller(Short bestSeller) {
		this.bestSeller = bestSeller;
	}
}
