/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;
import java.util.Date;

/**
 * Hateoas resource associated with BookOrder.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class BookOrderResource extends ResourceSupport {

	// Because id is reserved in parent class, we can't override the getter.
	@SuppressWarnings("unused")
    private Integer id;  
    private String shopCode;  
    private String customerCode;  
    private String employeeCode;  
    private Date date;  
    private Integer state;  

	// Constructor
	public BookOrderResource() {
		// Needed empty constructor for serialization
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getShopCode() {
		return this.shopCode;
	}
	public void setShopCode(String shopCode) {
		this.shopCode = shopCode;
	}
	public String getCustomerCode() {
		return this.customerCode;
	}
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}
	public String getEmployeeCode() {
		return this.employeeCode;
	}
	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}
	public Date getDate() {
		return this.date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public Integer getState() {
		return this.state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
}
