/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;

/**
 * Hateoas resource associated with Country.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class CountryResource extends ResourceSupport {

    private String code;  
    private String name;  

	// Constructor
	public CountryResource() {
		// Needed empty constructor for serialization
	}

	public String getCode() {
		return this.code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
}
