/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;

/**
 * Hateoas resource associated with Customer.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class CustomerResource extends ResourceSupport {

    private String code;  
    private String countryCode;  
    private String firstName;  
    private String lastName;  
    private String login;  
    private String password;  
    private Integer age;  
    private String city;  
    private Integer zipCode;  
    private String phone;  
    private Short reviewer;  

	// Constructor
	public CustomerResource() {
		// Needed empty constructor for serialization
	}

	public String getCode() {
		return this.code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getCountryCode() {
		return this.countryCode;
	}
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
	public String getFirstName() {
		return this.firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return this.lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getLogin() {
		return this.login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	public String getPassword() {
		return this.password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Integer getAge() {
		return this.age;
	}
	public void setAge(Integer age) {
		this.age = age;
	}
	public String getCity() {
		return this.city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public Integer getZipCode() {
		return this.zipCode;
	}
	public void setZipCode(Integer zipCode) {
		this.zipCode = zipCode;
	}
	public String getPhone() {
		return this.phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public Short getReviewer() {
		return this.reviewer;
	}
	public void setReviewer(Short reviewer) {
		this.reviewer = reviewer;
	}
}
