/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;
import java.util.Date;

/**
 * Hateoas resource associated with Review.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class ReviewResource extends ResourceSupport {

    private String customerCode;  
    private Integer bookId;  
    private String reviewText;  
    private Integer reviewNote;  
    private Date creation;  
    private Date lastUpdate;  

	// Constructor
	public ReviewResource() {
		// Needed empty constructor for serialization
	}

	public String getCustomerCode() {
		return this.customerCode;
	}
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}
	public Integer getBookId() {
		return this.bookId;
	}
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}
	public String getReviewText() {
		return this.reviewText;
	}
	public void setReviewText(String reviewText) {
		this.reviewText = reviewText;
	}
	public Integer getReviewNote() {
		return this.reviewNote;
	}
	public void setReviewNote(Integer reviewNote) {
		this.reviewNote = reviewNote;
	}
	public Date getCreation() {
		return this.creation;
	}
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	public Date getLastUpdate() {
		return this.lastUpdate;
	}
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}
