/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.AuthorResource;
import org.demo.entity.Author;

import fr.xebia.extras.selma.Mapper;

/**
 * AuthorResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface AuthorMapper {

	// This will build a fresh new AuthorResource with in infos
	AuthorResource map(Author in);

	Author map(AuthorResource in);

	// This will update the given Author
	Author map(AuthorResource in, Author out);

	// this will build a fresh list of AuthorResource with in infos
	List<AuthorResource> map(List<Author> in);
}
