/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.BadgeResource;
import org.demo.entity.Badge;

import fr.xebia.extras.selma.Mapper;

/**
 * BadgeResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface BadgeMapper {

	// This will build a fresh new BadgeResource with in infos
	BadgeResource map(Badge in);

	Badge map(BadgeResource in);

	// This will update the given Author
	Badge map(BadgeResource in, Badge out);

	// this will build a fresh list of BadgeResource with in infos
	List<BadgeResource> map(List<Badge> in);
}
