/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.BookOrderItemResource;
import org.demo.entity.BookOrderItem;

import fr.xebia.extras.selma.Mapper;

/**
 * BookOrderItemResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface BookOrderItemMapper {

	// This will build a fresh new BookOrderItemResource with in infos
	BookOrderItemResource map(BookOrderItem in);

	BookOrderItem map(BookOrderItemResource in);

	// This will update the given Author
	BookOrderItem map(BookOrderItemResource in, BookOrderItem out);

	// this will build a fresh list of BookOrderItemResource with in infos
	List<BookOrderItemResource> map(List<BookOrderItem> in);
}
