/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.BookResource;
import org.demo.entity.Book;

import fr.xebia.extras.selma.Mapper;

/**
 * BookResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface BookMapper {

	// This will build a fresh new BookResource with in infos
	BookResource map(Book in);

	Book map(BookResource in);

	// This will update the given Author
	Book map(BookResource in, Book out);

	// this will build a fresh list of BookResource with in infos
	List<BookResource> map(List<Book> in);
}
