/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.EmployeeGroupResource;
import org.demo.entity.EmployeeGroup;

import fr.xebia.extras.selma.Mapper;

/**
 * EmployeeGroupResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface EmployeeGroupMapper {

	// This will build a fresh new EmployeeGroupResource with in infos
	EmployeeGroupResource map(EmployeeGroup in);

	EmployeeGroup map(EmployeeGroupResource in);

	// This will update the given Author
	EmployeeGroup map(EmployeeGroupResource in, EmployeeGroup out);

	// this will build a fresh list of EmployeeGroupResource with in infos
	List<EmployeeGroupResource> map(List<EmployeeGroup> in);
}
