/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.EmployeeResource;
import org.demo.entity.Employee;

import fr.xebia.extras.selma.Mapper;

/**
 * EmployeeResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface EmployeeMapper {

	// This will build a fresh new EmployeeResource with in infos
	EmployeeResource map(Employee in);

	Employee map(EmployeeResource in);

	// This will update the given Author
	Employee map(EmployeeResource in, Employee out);

	// this will build a fresh list of EmployeeResource with in infos
	List<EmployeeResource> map(List<Employee> in);
}
