/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.AuthorController;
import org.demo.controller.mapper.AuthorMapper;
import org.demo.controller.resource.AuthorResource;
import org.demo.entity.Author;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class AuthorResourceAssembler extends ResourceAssemblerSupport<Author, AuthorResource> {

	// declare the mapper
	private AuthorMapper authorMapper;

	public AuthorResourceAssembler() {
		super(AuthorController.class, AuthorResource.class);
		authorMapper = Selma.builder(AuthorMapper.class).build();
	}

	@Override
	public AuthorResource toResource(Author author) {
		// Basic mapping
		final AuthorResource resource = authorMapper.map(author);
		resource.setId(author.getId());

		// adding hateoas links
		resource.add(linkTo(AuthorController.class).slash(author.getId()).withSelfRel());
		return resource;
	}

}
