/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.BadgeController;
import org.demo.controller.mapper.BadgeMapper;
import org.demo.controller.resource.BadgeResource;
import org.demo.entity.Badge;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class BadgeResourceAssembler extends ResourceAssemblerSupport<Badge, BadgeResource> {

	// declare the mapper
	private BadgeMapper badgeMapper;

	public BadgeResourceAssembler() {
		super(BadgeController.class, BadgeResource.class);
		badgeMapper = Selma.builder(BadgeMapper.class).build();
	}

	@Override
	public BadgeResource toResource(Badge badge) {
		// Basic mapping
		final BadgeResource resource = badgeMapper.map(badge);

		// adding hateoas links
		resource.add(linkTo(BadgeController.class).slash(badge.getBadgeNumber()).withSelfRel());
		return resource;
	}

}
