/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.CountryController;
import org.demo.controller.mapper.CountryMapper;
import org.demo.controller.resource.CountryResource;
import org.demo.entity.Country;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class CountryResourceAssembler extends ResourceAssemblerSupport<Country, CountryResource> {

	// declare the mapper
	private CountryMapper countryMapper;

	public CountryResourceAssembler() {
		super(CountryController.class, CountryResource.class);
		countryMapper = Selma.builder(CountryMapper.class).build();
	}

	@Override
	public CountryResource toResource(Country country) {
		// Basic mapping
		final CountryResource resource = countryMapper.map(country);

		// adding hateoas links
		resource.add(linkTo(CountryController.class).slash(country.getCode()).withSelfRel());
		return resource;
	}

}
