/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.CustomerController;
import org.demo.controller.mapper.CustomerMapper;
import org.demo.controller.resource.CustomerResource;
import org.demo.entity.Customer;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class CustomerResourceAssembler extends ResourceAssemblerSupport<Customer, CustomerResource> {

	// declare the mapper
	private CustomerMapper customerMapper;

	public CustomerResourceAssembler() {
		super(CustomerController.class, CustomerResource.class);
		customerMapper = Selma.builder(CustomerMapper.class).build();
	}

	@Override
	public CustomerResource toResource(Customer customer) {
		// Basic mapping
		final CustomerResource resource = customerMapper.map(customer);

		// adding hateoas links
		resource.add(linkTo(CustomerController.class).slash(customer.getCode()).withSelfRel());
		return resource;
	}

}
