/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.EmployeeController;
import org.demo.controller.mapper.EmployeeMapper;
import org.demo.controller.resource.EmployeeResource;
import org.demo.entity.Employee;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class EmployeeResourceAssembler extends ResourceAssemblerSupport<Employee, EmployeeResource> {

	// declare the mapper
	private EmployeeMapper employeeMapper;

	public EmployeeResourceAssembler() {
		super(EmployeeController.class, EmployeeResource.class);
		employeeMapper = Selma.builder(EmployeeMapper.class).build();
	}

	@Override
	public EmployeeResource toResource(Employee employee) {
		// Basic mapping
		final EmployeeResource resource = employeeMapper.map(employee);

		// adding hateoas links
		resource.add(linkTo(EmployeeController.class).slash(employee.getCode()).withSelfRel());
		return resource;
	}

}
