/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.ReviewController;
import org.demo.controller.mapper.ReviewMapper;
import org.demo.controller.resource.ReviewResource;
import org.demo.entity.Review;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class ReviewResourceAssembler extends ResourceAssemblerSupport<Review, ReviewResource> {

	// declare the mapper
	private ReviewMapper reviewMapper;

	public ReviewResourceAssembler() {
		super(ReviewController.class, ReviewResource.class);
		reviewMapper = Selma.builder(ReviewMapper.class).build();
	}

	@Override
	public ReviewResource toResource(Review review) {
		// Basic mapping
		final ReviewResource resource = reviewMapper.map(review);

		// adding hateoas links
		resource.add(linkTo(ReviewController.class).slash(review.getCustomerCode()).slash(review.getBookId()).withSelfRel());
		return resource;
	}

}
