/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.ShopController;
import org.demo.controller.mapper.ShopMapper;
import org.demo.controller.resource.ShopResource;
import org.demo.entity.Shop;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class ShopResourceAssembler extends ResourceAssemblerSupport<Shop, ShopResource> {

	// declare the mapper
	private ShopMapper shopMapper;

	public ShopResourceAssembler() {
		super(ShopController.class, ShopResource.class);
		shopMapper = Selma.builder(ShopMapper.class).build();
	}

	@Override
	public ShopResource toResource(Shop shop) {
		// Basic mapping
		final ShopResource resource = shopMapper.map(shop);

		// adding hateoas links
		resource.add(linkTo(ShopController.class).slash(shop.getCode()).withSelfRel());
		return resource;
	}

}
