/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.SynopsisController;
import org.demo.controller.mapper.SynopsisMapper;
import org.demo.controller.resource.SynopsisResource;
import org.demo.entity.Synopsis;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
public class SynopsisResourceAssembler extends ResourceAssemblerSupport<Synopsis, SynopsisResource> {

	// declare the mapper
	private SynopsisMapper synopsisMapper;

	public SynopsisResourceAssembler() {
		super(SynopsisController.class, SynopsisResource.class);
		synopsisMapper = Selma.builder(SynopsisMapper.class).build();
	}

	@Override
	public SynopsisResource toResource(Synopsis synopsis) {
		// Basic mapping
		final SynopsisResource resource = synopsisMapper.map(synopsis);

		// adding hateoas links
		resource.add(linkTo(SynopsisController.class).slash(synopsis.getBookId()).withSelfRel());
		return resource;
	}

}
