/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "BookOrderItem" ( stored in table "BOOK_ORDER_ITEM" )
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
 @Embeddable
public class BookOrderItemKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="BOOK_ORDER_ID", nullable=false)
    private Integer bookOrderId ;
    @Column(name="BOOK_ID", nullable=false)
    private Integer bookId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BookOrderItemKey() {
        super();
    }

    public BookOrderItemKey(Integer bookOrderId, Integer bookId) {
        super();
        this.bookOrderId = bookOrderId ;
        this.bookId = bookId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setBookOrderId(Integer value) {
        this.bookOrderId = value;
    }
	public Integer getBookOrderId() {
        return this.bookOrderId;
    }

	public void setBookId(Integer value) {
        this.bookId = value;
    }
	public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(bookOrderId); 
		sb.append("|"); 
		sb.append(bookId); 
        return sb.toString();
    }
}
