/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "EmployeeGroup" ( stored in table "EMPLOYEE_GROUP" )
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
 @Embeddable
public class EmployeeGroupKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="EMPLOYEE_CODE", nullable=false, length=4)
    private String employeeCode ;
    @Column(name="GROUP_ID", nullable=false)
    private Short groupId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public EmployeeGroupKey() {
        super();
    }

    public EmployeeGroupKey(String employeeCode, Short groupId) {
        super();
        this.employeeCode = employeeCode ;
        this.groupId = groupId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setEmployeeCode(String value) {
        this.employeeCode = value;
    }
	public String getEmployeeCode() {
        return this.employeeCode;
    }

	public void setGroupId(Short value) {
        this.groupId = value;
    }
	public Short getGroupId() {
        return this.groupId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(employeeCode); 
		sb.append("|"); 
		sb.append(groupId); 
        return sb.toString();
    }
}
