/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "Review" ( stored in table "REVIEW" )
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
 @Embeddable
public class ReviewKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="CUSTOMER_CODE", nullable=false, length=5)
    private String customerCode ;
    @Column(name="BOOK_ID", nullable=false)
    private Integer bookId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ReviewKey() {
        super();
    }

    public ReviewKey(String customerCode, Integer bookId) {
        super();
        this.customerCode = customerCode ;
        this.bookId = bookId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setCustomerCode(String value) {
        this.customerCode = value;
    }
	public String getCustomerCode() {
        return this.customerCode;
    }

	public void setBookId(Integer value) {
        this.bookId = value;
    }
	public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(customerCode); 
		sb.append("|"); 
		sb.append(bookId); 
        return sb.toString();
    }
}
