/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.entity;


import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for Review entity stored in table REVIEW.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Entity
@Table(name="REVIEW", schema="ROOT" )
public class Review implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ReviewKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="REVIEW_TEXT", length=32700)
    private String reviewText ;     @Column(name="REVIEW_NOTE")
    private Integer reviewNote ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION")
    private Date creation ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATE")
    private Date lastUpdate ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Review() {
		super();
		this.compositePrimaryKey = new ReviewKey();       
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setCustomerCode(String customerCode) {
        this.compositePrimaryKey.setCustomerCode(customerCode) ;
    }
	public String getCustomerCode() {
        return this.compositePrimaryKey.getCustomerCode() ;
    }
	public void setBookId(Integer bookId) {
        this.compositePrimaryKey.setBookId(bookId) ;
    }
	public Integer getBookId() {
        return this.compositePrimaryKey.getBookId() ;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : REVIEW_TEXT (LONG VARCHAR) 
	public void setReviewText(String reviewText) {this.reviewText = reviewText;}
	public String getReviewText() {return this.reviewText;}

	//--- DATABASE MAPPING : REVIEW_NOTE (INTEGER) 
	public void setReviewNote(Integer reviewNote) {this.reviewNote = reviewNote;}
	public Integer getReviewNote() {return this.reviewNote;}

	//--- DATABASE MAPPING : CREATION (TIMESTAMP) 
	public void setCreation(Date creation) {this.creation = creation;}
	public Date getCreation() {return this.creation;}

	//--- DATABASE MAPPING : LAST_UPDATE (TIMESTAMP) 
	public void setLastUpdate(Date lastUpdate) {this.lastUpdate = lastUpdate;}
	public Date getLastUpdate() {return this.lastUpdate;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("[" + compositePrimaryKey + "]"); 
		sb.append(reviewText); 
		sb.append("|"); 
		sb.append(reviewNote); 
		sb.append("|"); 
		sb.append(creation); 
		sb.append("|"); 
		sb.append(lastUpdate); 
        return sb.toString();
    }
}