/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for Workgroup entity stored in table WORKGROUP.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Entity
@Table(name="WORKGROUP", schema="ROOT" )
public class Workgroup implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Short id ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAME", nullable=false, length=40)
    private String name ;     @Column(name="DESCRIPTION", nullable=false, length=600)
    private String description ;     @Temporal(TemporalType.DATE)
    @Column(name="CREATION_DATE", nullable=false)
    private Date creationDate ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Workgroup() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setId(Short id) {
        this.id = id ;
    }
	public Short getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : NAME (VARCHAR) 
	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}

	//--- DATABASE MAPPING : DESCRIPTION (VARCHAR) 
	public void setDescription(String description) {this.description = description;}
	public String getDescription() {return this.description;}

	//--- DATABASE MAPPING : CREATION_DATE (DATE) 
	public void setCreationDate(Date creationDate) {this.creationDate = creationDate;}
	public Date getCreationDate() {return this.creationDate;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(id); 
		sb.append(name); 
		sb.append("|"); 
		sb.append(description); 
		sb.append("|"); 
		sb.append(creationDate); 
        return sb.toString();
    }
}