/*
 * Created on 2022-03-14 ( Date ISO 2022-03-14 - Time 18:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package org.demo.controller;

import org.demo.controller.assembler.BookOrderResourceAssembler;
import org.demo.controller.resource.BookOrderResource;
import org.demo.entity.BookOrder;
import org.demo.service.BookOrderServiceImpl;
import org.demo.service.criteria.BookOrderCriteria;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Rest controller which produce Hal+json content (including hateoas metadata).
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@RestController
@RequestMapping(value = "/bookOrder", produces = "application/hal+json")
public class BookOrderController {

	private static final Logger LOGGER = LoggerFactory.getLogger(BookOrderController.class);

	private static final String NOT_FOUND ="BookOrder not found";

	@Autowired
	private BookOrderServiceImpl bookOrderService;

	@Autowired
	private PagedResourcesAssembler<BookOrder> pageAssember;

	private BookOrderResourceAssembler bookOrderResourceAssembler = new BookOrderResourceAssembler();

	@GetMapping
	public ResponseEntity<PagedResources<BookOrderResource>> search(Pageable pageable, BookOrderCriteria criteria) {
		LOGGER.info("BookOrders search [pageable={}|BookOrderCriteria={}", pageable, criteria);
		final Page<BookOrder> result = bookOrderService.search(pageable, criteria);
		LOGGER.info("Found {} bookOrders !", result.getSize());
		return new ResponseEntity<>(pageAssember.toResource(result, bookOrderResourceAssembler), HttpStatus.OK);
	}

	@GetMapping("{id}")
	public ResponseEntity<BookOrderResource> get(@PathVariable("id") Integer id) {
		LOGGER.info("BookOrder get with id {}", resolveIdForLogger(id));
		final BookOrder bookOrder = bookOrderService.get(id);
		if (bookOrder == null) {
			LOGGER.info(NOT_FOUND);
			return new ResponseEntity<>((BookOrderResource) null, HttpStatus.NOT_FOUND);
		}
		LOGGER.info("BookOrder found : {}", bookOrder);
		final BookOrderResource bookOrderResource = bookOrderResourceAssembler.toResource(bookOrder);
		return new ResponseEntity<>(bookOrderResource, HttpStatus.OK);
	}

	@PostMapping(consumes = "application/json")
	public ResponseEntity<BookOrderResource> create(@RequestBody BookOrder bookOrder) {
		LOGGER.info("BookOrder creation request : {}", bookOrder);
		if (bookOrderService.exist(bookOrder)) {
			LOGGER.info("BookOrder already exist ! : {}", bookOrder);
			return new ResponseEntity<>((BookOrderResource) null, HttpStatus.CONFLICT);
		} else {
			final BookOrder created = bookOrderService.create(bookOrder);
			LOGGER.info("Created bookOrder {}", created);
			return new ResponseEntity<>(bookOrderResourceAssembler.toResource(created), HttpStatus.OK);
		}
	}

	@PutMapping(value = "{id}", consumes = "application/json")
	public ResponseEntity<Void> update(@PathVariable("id") Integer id, @RequestBody BookOrder bookOrder) {
		LOGGER.info("BookOrder update request [id={} | bookOrder={}}", resolveIdForLogger(id), bookOrder);
		// force the id (use the id provided by the URL)
		bookOrder.setId(id);
		if (bookOrderService.save(bookOrder)) {
			LOGGER.info("BookOrder succesfully updated");
			return new ResponseEntity<>(HttpStatus.OK);
		} else {
			LOGGER.info(NOT_FOUND);
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}

	@DeleteMapping("{id}")
	public ResponseEntity<Void> delete(@PathVariable("id") Integer id) {
		LOGGER.info("BookOrder deletion request : {}", resolveIdForLogger(id));
		if (bookOrderService.delete(id)) {
			LOGGER.info("BookOrder succesfully deleted");
			return new ResponseEntity<>(HttpStatus.NO_CONTENT);
		} else {
			LOGGER.info(NOT_FOUND);
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer id) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(id));
		return ids.toString();
	}

}
